# permissions for end users to edit bindingconfigurations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  name: {{ include "ngrok-operator.fullname" . }}-bindingconfiguration-editor-role
rules:
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - bindingconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - bindingconfigurations/status
  verbs:
  - get
