# permissions for end users to view operatorconfigurations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  name: {{ include "ngrok-operator.fullname" . }}-operatorconfiguration-viewer-role
rules:
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - operatorconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - operatorconfigurations/status
  verbs:
  - get
