{{- if and .Values.features.ingress.enabled (not .Values.apiManager.config.oneClickDemoMode) }}
{{- $component := "agent" }}
{{- $rbacChecksum := include (print $.Template.BasePath "/agent/role.yaml") . | sha256sum }}
{{- $agent := .Values.agent }}
{{- $configChecksum := include "ngrok-operator.componentConfig" (dict "context" $ "config" $agent.config) | sha256sum }}
{{- $configEnvKeys := list
  (list "NGROK_OPERATOR_DESCRIPTION" "description")
  (list "NGROK_OPERATOR_REGION" "region")
  (list "NGROK_OPERATOR_ROOT_CAS" "rootCAs")
  (list "NGROK_OPERATOR_SERVER_ADDR" "serverAddr")
  (list "NGROK_OPERATOR_LOG_LEVEL" "log.level")
  (list "NGROK_OPERATOR_LOG_FORMAT" "log.format")
  (list "NGROK_OPERATOR_LOG_STACKTRACE_LEVEL" "log.stacktraceLevel")
  (list "NGROK_OPERATOR_FEATURES_INGRESS_ENABLED" "features.ingress.enabled")
  (list "NGROK_OPERATOR_FEATURES_INGRESS_WATCH_NAMESPACE" "features.ingress.watchNamespace")
  (list "NGROK_OPERATOR_FEATURES_GATEWAY_ENABLED" "features.gateway.enabled")
  (list "NGROK_OPERATOR_FEATURES_GATEWAY_DISABLE_REFERENCE_GRANTS" "features.gateway.disableReferenceGrants")
  (list "NGROK_OPERATOR_FEATURES_BINDINGS_ENABLED" "features.bindings.enabled")
  (list "NGROK_OPERATOR_FEATURES_DEFAULT_DOMAIN_RECLAIM_POLICY" "features.defaultDomainReclaimPolicy")
}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  name: {{ include "ngrok-operator.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with (include "ngrok-operator.commonAnnotations" .) }}
    {{- . | nindent 4 }}
    {{- end }}
    checksum/rbac: {{ $rbacChecksum }}
spec:
  replicas: {{ $agent.replicaCount }}
  {{- if $agent.updateStrategy }}
  strategy:
    {{- toYaml $agent.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ngrok-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      annotations:
        {{- if $agent.podAnnotations }}
          {{- toYaml $agent.podAnnotations | nindent 8 }}
        {{- end }}
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
        checksum/rbac: {{ $rbacChecksum }}
        checksum/config: {{ $configChecksum }}
      labels:
        {{- include "ngrok-operator.selectorLabels" . | nindent 8 }}
        {{- if $agent.podLabels }}
          {{- toYaml $agent.podLabels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      {{- if $agent.priorityClassName }}
      priorityClassName: {{ $agent.priorityClassName | quote }}
      {{- end }}
      {{- if $agent.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $agent.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if $agent.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" $agent.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" $agent.podAffinityPreset "component" $component "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" $agent.podAntiAffinityPreset "component" $component "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" $agent.nodeAffinityPreset.type "key" $agent.nodeAffinityPreset.key "values" $agent.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- with $agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ with $agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $agent.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "ngrok-operator.agent.serviceAccountName" . }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: agent
        image: {{ include "ngrok-operator.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /ngrok-operator
        args:
        - agent-manager
        - --release-name={{ .Release.Name }}
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        - --manager-name={{ include "ngrok-operator.fullname" . }}-agent-manager
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: NGROK_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              key: AUTHTOKEN
              name: {{ include "ngrok-operator.credentialsSecretName" . }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HELM_RELEASE_NAME
          value: {{ .Release.Name | quote }}
        {{- include "ngrok-operator.configEnv" (dict "context" $ "component" "agent" "keys" $configEnvKeys) | trim | nindent 8 }}
        {{- range $key, $value := $agent.extraEnv }}
        - name: {{ $key }}
          value: {{- toYaml $value | nindent 12 }}
        {{- end }}
        {{- if $agent.extraVolumeMounts }}
        volumeMounts:
        {{- toYaml $agent.extraVolumeMounts | nindent 8 }}
        {{- end }}
        {{- if $agent.lifecycle }}
        lifecycle:
        {{ toYaml $agent.lifecycle | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
        {{- toYaml $agent.resources | nindent 10 }}
      {{- if $agent.extraVolumes }}
      volumes:
        {{- toYaml $agent.extraVolumes | nindent 6 }}
      {{- end }}
{{- end }}
