area/ci:
- .github/workflows/**/*
- .golangci.yml

area/controller:
- '**/*.go'
- Dockerfile

area/devenv:
- .devcontainer/**/*
- flake.nix
- flake.lock

area/helm-chart:
- helm/**/*

area/release:
- docs/releases.md
- VERSION
- helm/ngrok-operator/Chart.yaml

documentation:
- docs/**/*

meta/project:
- .github/ISSUE_TEMPLATE/**/*
- .github/CODEOWNERS
- .github/labeler.yaml
- .github/PULL_REQUEST_TEMPLATE.md

testing:
- scripts/e2e.sh
