area/ci:
- changed-files:
    - any-glob-to-any-file:
        - .github/workflows/**/*
        - .golangci.yml

area/controller:
- changed-files:
    - any-glob-to-any-file:
        - '**/*.go'
        - Dockerfile

area/devenv:
- changed-files:
    - any-glob-to-any-file:
        - .devcontainer/**/*
        - flake.nix
        - flake.lock

area/helm-chart:
- changed-files:
    - any-glob-to-any-file:
        - helm/**/*

area/release:
- changed-files:
    - any-glob-to-any-file:
        - docs/releases.md
        - VERSION
        - helm/ngrok-operator/Chart.yaml

documentation:
- changed-files:
    - any-glob-to-any-file:
        - docs/**/*

meta/project:
- changed-files:
    - any-glob-to-any-file:
        - .github/ISSUE_TEMPLATE/**/*
        - .github/CODEOWNERS
        - .github/labeler.yml
        - .github/PULL_REQUEST_TEMPLATE.md

testing:
- changed-files:
    - any-glob-to-any-file:
        - scripts/e2e.sh
