//go:build !ignore_autogenerated

/*
MIT License

Copyright (c) 2025 ngrok, Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"encoding/json"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpoint) DeepCopyInto(out *AgentEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpoint.
func (in *AgentEndpoint) DeepCopy() *AgentEndpoint {
	if in == nil {
		return nil
	}
	out := new(AgentEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointList) DeepCopyInto(out *AgentEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointList.
func (in *AgentEndpointList) DeepCopy() *AgentEndpointList {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointSpec) DeepCopyInto(out *AgentEndpointSpec) {
	*out = *in
	in.Upstream.DeepCopyInto(&out.Upstream)
	if in.TrafficPolicy != nil {
		in, out := &in.TrafficPolicy, &out.TrafficPolicy
		*out = new(TrafficPolicyCfg)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientCertificateRefs != nil {
		in, out := &in.ClientCertificateRefs, &out.ClientCertificateRefs
		*out = make([]K8sObjectRefOptionalNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLSTermination != nil {
		in, out := &in.TLSTermination, &out.TLSTermination
		*out = new(EndpointTLSTermination)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointSpec.
func (in *AgentEndpointSpec) DeepCopy() *AgentEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointStatus) DeepCopyInto(out *AgentEndpointStatus) {
	*out = *in
	if in.DomainRef != nil {
		in, out := &in.DomainRef, &out.DomainRef
		*out = new(K8sObjectRefOptionalNamespace)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointStatus.
func (in *AgentEndpointStatus) DeepCopy() *AgentEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingEndpoint) DeepCopyInto(out *BindingEndpoint) {
	*out = *in
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingEndpoint.
func (in *BindingEndpoint) DeepCopy() *BindingEndpoint {
	if in == nil {
		return nil
	}
	out := new(BindingEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundEndpoint) DeepCopyInto(out *BoundEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundEndpoint.
func (in *BoundEndpoint) DeepCopy() *BoundEndpoint {
	if in == nil {
		return nil
	}
	out := new(BoundEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoundEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundEndpointList) DeepCopyInto(out *BoundEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoundEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundEndpointList.
func (in *BoundEndpointList) DeepCopy() *BoundEndpointList {
	if in == nil {
		return nil
	}
	out := new(BoundEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoundEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundEndpointSpec) DeepCopyInto(out *BoundEndpointSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundEndpointSpec.
func (in *BoundEndpointSpec) DeepCopy() *BoundEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(BoundEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundEndpointStatus) DeepCopyInto(out *BoundEndpointStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]BindingEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetServiceRef != nil {
		in, out := &in.TargetServiceRef, &out.TargetServiceRef
		*out = new(K8sObjectRefOptionalNamespace)
		(*in).DeepCopyInto(*out)
	}
	if in.UpstreamServiceRef != nil {
		in, out := &in.UpstreamServiceRef, &out.UpstreamServiceRef
		*out = new(K8sObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundEndpointStatus.
func (in *BoundEndpointStatus) DeepCopy() *BoundEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(BoundEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEndpoint) DeepCopyInto(out *CloudEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEndpoint.
func (in *CloudEndpoint) DeepCopy() *CloudEndpoint {
	if in == nil {
		return nil
	}
	out := new(CloudEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEndpointList) DeepCopyInto(out *CloudEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEndpointList.
func (in *CloudEndpointList) DeepCopy() *CloudEndpointList {
	if in == nil {
		return nil
	}
	out := new(CloudEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEndpointSpec) DeepCopyInto(out *CloudEndpointSpec) {
	*out = *in
	if in.TrafficPolicy != nil {
		in, out := &in.TrafficPolicy, &out.TrafficPolicy
		*out = new(TrafficPolicyCfg)
		(*in).DeepCopyInto(*out)
	}
	if in.PoolingEnabled != nil {
		in, out := &in.PoolingEnabled, &out.PoolingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEndpointSpec.
func (in *CloudEndpointSpec) DeepCopy() *CloudEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(CloudEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEndpointStatus) DeepCopyInto(out *CloudEndpointStatus) {
	*out = *in
	if in.DomainRef != nil {
		in, out := &in.DomainRef, &out.DomainRef
		*out = new(K8sObjectRefOptionalNamespace)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEndpointStatus.
func (in *CloudEndpointStatus) DeepCopy() *CloudEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(CloudEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Domain) DeepCopyInto(out *Domain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Domain.
func (in *Domain) DeepCopy() *Domain {
	if in == nil {
		return nil
	}
	out := new(Domain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Domain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainList) DeepCopyInto(out *DomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Domain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainList.
func (in *DomainList) DeepCopy() *DomainList {
	if in == nil {
		return nil
	}
	out := new(DomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainResolvesToEntry) DeepCopyInto(out *DomainResolvesToEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainResolvesToEntry.
func (in *DomainResolvesToEntry) DeepCopy() *DomainResolvesToEntry {
	if in == nil {
		return nil
	}
	out := new(DomainResolvesToEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainSpec) DeepCopyInto(out *DomainSpec) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResolvesTo != nil {
		in, out := &in.ResolvesTo, &out.ResolvesTo
		*out = new([]DomainResolvesToEntry)
		if **in != nil {
			in, out := *in, *out
			*out = make([]DomainResolvesToEntry, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainSpec.
func (in *DomainSpec) DeepCopy() *DomainSpec {
	if in == nil {
		return nil
	}
	out := new(DomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainStatus) DeepCopyInto(out *DomainStatus) {
	*out = *in
	if in.ResolvesTo != nil {
		in, out := &in.ResolvesTo, &out.ResolvesTo
		*out = new([]DomainResolvesToEntry)
		if **in != nil {
			in, out := *in, *out
			*out = make([]DomainResolvesToEntry, len(*in))
			copy(*out, *in)
		}
	}
	if in.CNAMETarget != nil {
		in, out := &in.CNAMETarget, &out.CNAMETarget
		*out = new(string)
		**out = **in
	}
	if in.ACMEChallengeCNAMETarget != nil {
		in, out := &in.ACMEChallengeCNAMETarget, &out.ACMEChallengeCNAMETarget
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(DomainStatusCertificateInfo)
		**out = **in
	}
	if in.CertificateManagementPolicy != nil {
		in, out := &in.CertificateManagementPolicy, &out.CertificateManagementPolicy
		*out = new(DomainStatusCertificateManagementPolicy)
		**out = **in
	}
	if in.CertificateManagementStatus != nil {
		in, out := &in.CertificateManagementStatus, &out.CertificateManagementStatus
		*out = new(DomainStatusCertificateManagementStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainStatus.
func (in *DomainStatus) DeepCopy() *DomainStatus {
	if in == nil {
		return nil
	}
	out := new(DomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainStatusCertificateInfo) DeepCopyInto(out *DomainStatusCertificateInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainStatusCertificateInfo.
func (in *DomainStatusCertificateInfo) DeepCopy() *DomainStatusCertificateInfo {
	if in == nil {
		return nil
	}
	out := new(DomainStatusCertificateInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainStatusCertificateManagementPolicy) DeepCopyInto(out *DomainStatusCertificateManagementPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainStatusCertificateManagementPolicy.
func (in *DomainStatusCertificateManagementPolicy) DeepCopy() *DomainStatusCertificateManagementPolicy {
	if in == nil {
		return nil
	}
	out := new(DomainStatusCertificateManagementPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainStatusCertificateManagementStatus) DeepCopyInto(out *DomainStatusCertificateManagementStatus) {
	*out = *in
	if in.RenewsAt != nil {
		in, out := &in.RenewsAt, &out.RenewsAt
		*out = (*in).DeepCopy()
	}
	if in.ProvisioningJob != nil {
		in, out := &in.ProvisioningJob, &out.ProvisioningJob
		*out = new(DomainStatusProvisioningJob)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainStatusCertificateManagementStatus.
func (in *DomainStatusCertificateManagementStatus) DeepCopy() *DomainStatusCertificateManagementStatus {
	if in == nil {
		return nil
	}
	out := new(DomainStatusCertificateManagementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainStatusProvisioningJob) DeepCopyInto(out *DomainStatusProvisioningJob) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.RetriesAt != nil {
		in, out := &in.RetriesAt, &out.RetriesAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainStatusProvisioningJob.
func (in *DomainStatusProvisioningJob) DeepCopy() *DomainStatusProvisioningJob {
	if in == nil {
		return nil
	}
	out := new(DomainStatusProvisioningJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainConfig) DeepCopyInto(out *DrainConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainConfig.
func (in *DrainConfig) DeepCopy() *DrainConfig {
	if in == nil {
		return nil
	}
	out := new(DrainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointMutualTLS) DeepCopyInto(out *EndpointMutualTLS) {
	*out = *in
	out.ClientCAsRef = in.ClientCAsRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointMutualTLS.
func (in *EndpointMutualTLS) DeepCopy() *EndpointMutualTLS {
	if in == nil {
		return nil
	}
	out := new(EndpointMutualTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointTLSTermination) DeepCopyInto(out *EndpointTLSTermination) {
	*out = *in
	out.ServerCertificateRef = in.ServerCertificateRef
	if in.MutualTLS != nil {
		in, out := &in.MutualTLS, &out.MutualTLS
		*out = new(EndpointMutualTLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointTLSTermination.
func (in *EndpointTLSTermination) DeepCopy() *EndpointTLSTermination {
	if in == nil {
		return nil
	}
	out := new(EndpointTLSTermination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointTarget) DeepCopyInto(out *EndpointTarget) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointTarget.
func (in *EndpointTarget) DeepCopy() *EndpointTarget {
	if in == nil {
		return nil
	}
	out := new(EndpointTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointUpstream) DeepCopyInto(out *EndpointUpstream) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(ApplicationProtocol)
		**out = **in
	}
	if in.ProxyProtocolVersion != nil {
		in, out := &in.ProxyProtocolVersion, &out.ProxyProtocolVersion
		*out = new(ProxyProtocolVersion)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointUpstream.
func (in *EndpointUpstream) DeepCopy() *EndpointUpstream {
	if in == nil {
		return nil
	}
	out := new(EndpointUpstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPolicy) DeepCopyInto(out *IPPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPolicy.
func (in *IPPolicy) DeepCopy() *IPPolicy {
	if in == nil {
		return nil
	}
	out := new(IPPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPolicyList) DeepCopyInto(out *IPPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPolicyList.
func (in *IPPolicyList) DeepCopy() *IPPolicyList {
	if in == nil {
		return nil
	}
	out := new(IPPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPolicyRule) DeepCopyInto(out *IPPolicyRule) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPolicyRule.
func (in *IPPolicyRule) DeepCopy() *IPPolicyRule {
	if in == nil {
		return nil
	}
	out := new(IPPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPolicyRuleStatus) DeepCopyInto(out *IPPolicyRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPolicyRuleStatus.
func (in *IPPolicyRuleStatus) DeepCopy() *IPPolicyRuleStatus {
	if in == nil {
		return nil
	}
	out := new(IPPolicyRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPolicySpec) DeepCopyInto(out *IPPolicySpec) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]IPPolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPolicySpec.
func (in *IPPolicySpec) DeepCopy() *IPPolicySpec {
	if in == nil {
		return nil
	}
	out := new(IPPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPolicyStatus) DeepCopyInto(out *IPPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]IPPolicyRuleStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPolicyStatus.
func (in *IPPolicyStatus) DeepCopy() *IPPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(IPPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sObjectRef) DeepCopyInto(out *K8sObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sObjectRef.
func (in *K8sObjectRef) DeepCopy() *K8sObjectRef {
	if in == nil {
		return nil
	}
	out := new(K8sObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sObjectRefOptionalNamespace) DeepCopyInto(out *K8sObjectRefOptionalNamespace) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sObjectRefOptionalNamespace.
func (in *K8sObjectRefOptionalNamespace) DeepCopy() *K8sObjectRefOptionalNamespace {
	if in == nil {
		return nil
	}
	out := new(K8sObjectRefOptionalNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperator) DeepCopyInto(out *KubernetesOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperator.
func (in *KubernetesOperator) DeepCopy() *KubernetesOperator {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorBinding) DeepCopyInto(out *KubernetesOperatorBinding) {
	*out = *in
	if in.EndpointSelectors != nil {
		in, out := &in.EndpointSelectors, &out.EndpointSelectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IngressEndpoint != nil {
		in, out := &in.IngressEndpoint, &out.IngressEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorBinding.
func (in *KubernetesOperatorBinding) DeepCopy() *KubernetesOperatorBinding {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorDeployment) DeepCopyInto(out *KubernetesOperatorDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorDeployment.
func (in *KubernetesOperatorDeployment) DeepCopy() *KubernetesOperatorDeployment {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorList) DeepCopyInto(out *KubernetesOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubernetesOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorList.
func (in *KubernetesOperatorList) DeepCopy() *KubernetesOperatorList {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorSpec) DeepCopyInto(out *KubernetesOperatorSpec) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnabledFeatures != nil {
		in, out := &in.EnabledFeatures, &out.EnabledFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(KubernetesOperatorDeployment)
		**out = **in
	}
	if in.Binding != nil {
		in, out := &in.Binding, &out.Binding
		*out = new(KubernetesOperatorBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.Drain != nil {
		in, out := &in.Drain, &out.Drain
		*out = new(DrainConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorSpec.
func (in *KubernetesOperatorSpec) DeepCopy() *KubernetesOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorStatus) DeepCopyInto(out *KubernetesOperatorStatus) {
	*out = *in
	if in.DrainErrors != nil {
		in, out := &in.DrainErrors, &out.DrainErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorStatus.
func (in *KubernetesOperatorStatus) DeepCopy() *KubernetesOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetMetadata) DeepCopyInto(out *TargetMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetMetadata.
func (in *TargetMetadata) DeepCopy() *TargetMetadata {
	if in == nil {
		return nil
	}
	out := new(TargetMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficPolicy) DeepCopyInto(out *TrafficPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficPolicy.
func (in *TrafficPolicy) DeepCopy() *TrafficPolicy {
	if in == nil {
		return nil
	}
	out := new(TrafficPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficPolicyCfg) DeepCopyInto(out *TrafficPolicyCfg) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.TargetRef != nil {
		in, out := &in.TargetRef, &out.TargetRef
		*out = new(K8sObjectRefOptionalNamespace)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficPolicyCfg.
func (in *TrafficPolicyCfg) DeepCopy() *TrafficPolicyCfg {
	if in == nil {
		return nil
	}
	out := new(TrafficPolicyCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficPolicyList) DeepCopyInto(out *TrafficPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrafficPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficPolicyList.
func (in *TrafficPolicyList) DeepCopy() *TrafficPolicyList {
	if in == nil {
		return nil
	}
	out := new(TrafficPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficPolicySpec) DeepCopyInto(out *TrafficPolicySpec) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficPolicySpec.
func (in *TrafficPolicySpec) DeepCopy() *TrafficPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TrafficPolicySpec)
	in.DeepCopyInto(out)
	return out
}
