package labels

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// prefix is the unified label prefix introduced in the ngrok.com migration.
const prefix = "ngrok.com/"

// IsOperatorManaged reports whether the object was generated by an operator
// reconciler (Ingress/Gateway/Service) rather than authored by a user.
// Generated objects carry either a controller OwnerReference (Service path) or
// the operator's controller label (managerdriver Ingress/Gateway path). This is
// used to suppress deprecation events the user cannot act on.
func IsOperatorManaged(obj metav1.Object) bool {
	for _, ref := range obj.GetOwnerReferences() {
		if ref.Controller != nil && *ref.Controller {
			return true
		}
	}
	if _, ok := obj.GetLabels()[ControllerName]; ok {
		return true
	}
	// LEGACY-PREFIX-MIGRATION: also match the legacy controller label so objects
	// stamped by a pre-migration operator are still recognized as managed.
	if _, ok := obj.GetLabels()[LegacyControllerName]; ok {
		return true
	}
	return false
}

// LEGACY-PREFIX-MIGRATION: BEGIN
// Deprecated label prefix retained for read-side compatibility.
// LEGACY-PREFIX-MIGRATION (read-side cleanup): delete this const and every
// `Legacy*` symbol downstream of it.
const legacyPrefix = "k8s.ngrok.com/"

// LEGACY-PREFIX-MIGRATION: END
