package controller

import (
	commonv1alpha1 "github.com/ngrok/ngrok-operator/api/common/v1alpha1"
	"github.com/ngrok/ngrok-operator/internal/controller/labels"
	v1 "k8s.io/api/core/v1"
	"k8s.io/client-go/tools/events"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// WarnIfDeprecatedMetadata emits a DeprecatedField warning event when a
// user-authored object still carries its metadata as a raw JSON string rather
// than the canonical map form. Objects generated by the operator are skipped —
// they intentionally keep the string form during the migration window for
// rollback safety and the user cannot act on the event. Objects that merely
// took the default value are also skipped (see MetadataValue.UsesDeprecatedStringForm).
//
// LEGACY-metadata-format: delete this helper and its call sites in the cleanup release.
func WarnIfDeprecatedMetadata(recorder events.EventRecorder, obj client.Object, md *commonv1alpha1.MetadataValue) {
	if recorder == nil || labels.IsOperatorManaged(obj) {
		return
	}
	if md.UsesDeprecatedStringForm() {
		recorder.Eventf(obj, nil, v1.EventTypeWarning, "DeprecatedField", "Reconcile",
			"spec.metadata is set as a raw JSON string, which is deprecated; use a map of string key/value pairs instead")
	}
	if md.HasNonStringValues() {
		recorder.Eventf(obj, nil, v1.EventTypeWarning, "InvalidField", "Reconcile",
			"spec.metadata contains values that are not strings; only a flat map of string key/value pairs is supported and non-string values will be rejected in a future release")
	}
}
