apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: ngrok-operator
    meta.helm.sh/release-namespace: ngrok-operator
  creationTimestamp: "2026-04-07T17:14:32Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ngrok-operator-agent-role
  resourceVersion: "844"
  uid: c6b95f79-abad-4697-8631-8f956f5ffcd9
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.k8s.ngrok.com
  resources:
  - domains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - agentendpoints
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - agentendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - agentendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - kubernetesoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - ngroktrafficpolicies
  verbs:
  - get
  - list
  - watch
