# ClusterRole: ngrok-operator-ippolicy-viewer-role
# Generated: 2026-04-07T15:32:47Z

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: ngrok-operator
    meta.helm.sh/release-namespace: ngrok-operator
  creationTimestamp: "2026-04-07T15:25:18Z"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: ngrok-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ngrok-operator
    app.kubernetes.io/part-of: ngrok-operator
    app.kubernetes.io/version: 0.20.3
    helm.sh/chart: ngrok-operator-0.22.2
  name: ngrok-operator-ippolicy-viewer-role
  resourceVersion: "629"
  uid: 186db47f-2ef6-41a9-a9e4-7a531e9db984
rules:
- apiGroups:
  - ingress.k8s.ngrok.com
  resources:
  - ippolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.k8s.ngrok.com
  resources:
  - ippolicies/status
  verbs:
  - get
