apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: ngrok-operator
    meta.helm.sh/release-namespace: ngrok-operator
  creationTimestamp: "2026-04-07T17:14:33Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ngrok-operator-leader-election-role
  namespace: ngrok-operator
  resourceVersion: "868"
  uid: 24981661-1580-46f8-9b3b-485d3a1b459f
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
