//go:build !ignore_autogenerated

/*
MIT License

Copyright (c) 2025 ngrok, Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	commonv1alpha1 "github.com/ngrok/ngrok-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpoint) DeepCopyInto(out *AgentEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpoint.
func (in *AgentEndpoint) DeepCopy() *AgentEndpoint {
	if in == nil {
		return nil
	}
	out := new(AgentEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointList) DeepCopyInto(out *AgentEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointList.
func (in *AgentEndpointList) DeepCopy() *AgentEndpointList {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointSpec) DeepCopyInto(out *AgentEndpointSpec) {
	*out = *in
	in.Upstream.DeepCopyInto(&out.Upstream)
	if in.TrafficPolicy != nil {
		in, out := &in.TrafficPolicy, &out.TrafficPolicy
		*out = new(TrafficPolicyCfg)
		(*in).DeepCopyInto(*out)
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientCertificateRefs != nil {
		in, out := &in.ClientCertificateRefs, &out.ClientCertificateRefs
		*out = make([]K8sObjectRefOptionalNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointSpec.
func (in *AgentEndpointSpec) DeepCopy() *AgentEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointStatus) DeepCopyInto(out *AgentEndpointStatus) {
	*out = *in
	if in.DomainRef != nil {
		in, out := &in.DomainRef, &out.DomainRef
		*out = new(K8sObjectRefOptionalNamespace)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointStatus.
func (in *AgentEndpointStatus) DeepCopy() *AgentEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEndpoint) DeepCopyInto(out *CloudEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEndpoint.
func (in *CloudEndpoint) DeepCopy() *CloudEndpoint {
	if in == nil {
		return nil
	}
	out := new(CloudEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEndpointList) DeepCopyInto(out *CloudEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEndpointList.
func (in *CloudEndpointList) DeepCopy() *CloudEndpointList {
	if in == nil {
		return nil
	}
	out := new(CloudEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEndpointSpec) DeepCopyInto(out *CloudEndpointSpec) {
	*out = *in
	if in.PoolingEnabled != nil {
		in, out := &in.PoolingEnabled, &out.PoolingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TrafficPolicy != nil {
		in, out := &in.TrafficPolicy, &out.TrafficPolicy
		*out = new(NgrokTrafficPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEndpointSpec.
func (in *CloudEndpointSpec) DeepCopy() *CloudEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(CloudEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEndpointStatus) DeepCopyInto(out *CloudEndpointStatus) {
	*out = *in
	if in.DomainRef != nil {
		in, out := &in.DomainRef, &out.DomainRef
		*out = new(K8sObjectRefOptionalNamespace)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEndpointStatus.
func (in *CloudEndpointStatus) DeepCopy() *CloudEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(CloudEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainConfig) DeepCopyInto(out *DrainConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainConfig.
func (in *DrainConfig) DeepCopy() *DrainConfig {
	if in == nil {
		return nil
	}
	out := new(DrainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointUpstream) DeepCopyInto(out *EndpointUpstream) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(commonv1alpha1.ApplicationProtocol)
		**out = **in
	}
	if in.ProxyProtocolVersion != nil {
		in, out := &in.ProxyProtocolVersion, &out.ProxyProtocolVersion
		*out = new(commonv1alpha1.ProxyProtocolVersion)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointUpstream.
func (in *EndpointUpstream) DeepCopy() *EndpointUpstream {
	if in == nil {
		return nil
	}
	out := new(EndpointUpstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sObjectRef) DeepCopyInto(out *K8sObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sObjectRef.
func (in *K8sObjectRef) DeepCopy() *K8sObjectRef {
	if in == nil {
		return nil
	}
	out := new(K8sObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sObjectRefOptionalNamespace) DeepCopyInto(out *K8sObjectRefOptionalNamespace) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sObjectRefOptionalNamespace.
func (in *K8sObjectRefOptionalNamespace) DeepCopy() *K8sObjectRefOptionalNamespace {
	if in == nil {
		return nil
	}
	out := new(K8sObjectRefOptionalNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperator) DeepCopyInto(out *KubernetesOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperator.
func (in *KubernetesOperator) DeepCopy() *KubernetesOperator {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorBinding) DeepCopyInto(out *KubernetesOperatorBinding) {
	*out = *in
	if in.EndpointSelectors != nil {
		in, out := &in.EndpointSelectors, &out.EndpointSelectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IngressEndpoint != nil {
		in, out := &in.IngressEndpoint, &out.IngressEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorBinding.
func (in *KubernetesOperatorBinding) DeepCopy() *KubernetesOperatorBinding {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorDeployment) DeepCopyInto(out *KubernetesOperatorDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorDeployment.
func (in *KubernetesOperatorDeployment) DeepCopy() *KubernetesOperatorDeployment {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorList) DeepCopyInto(out *KubernetesOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubernetesOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorList.
func (in *KubernetesOperatorList) DeepCopy() *KubernetesOperatorList {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorSpec) DeepCopyInto(out *KubernetesOperatorSpec) {
	*out = *in
	if in.EnabledFeatures != nil {
		in, out := &in.EnabledFeatures, &out.EnabledFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(KubernetesOperatorDeployment)
		**out = **in
	}
	if in.Binding != nil {
		in, out := &in.Binding, &out.Binding
		*out = new(KubernetesOperatorBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.Drain != nil {
		in, out := &in.Drain, &out.Drain
		*out = new(DrainConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorSpec.
func (in *KubernetesOperatorSpec) DeepCopy() *KubernetesOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesOperatorStatus) DeepCopyInto(out *KubernetesOperatorStatus) {
	*out = *in
	if in.DrainErrors != nil {
		in, out := &in.DrainErrors, &out.DrainErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesOperatorStatus.
func (in *KubernetesOperatorStatus) DeepCopy() *KubernetesOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(KubernetesOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NgrokTrafficPolicy) DeepCopyInto(out *NgrokTrafficPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NgrokTrafficPolicy.
func (in *NgrokTrafficPolicy) DeepCopy() *NgrokTrafficPolicy {
	if in == nil {
		return nil
	}
	out := new(NgrokTrafficPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NgrokTrafficPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NgrokTrafficPolicyList) DeepCopyInto(out *NgrokTrafficPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NgrokTrafficPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NgrokTrafficPolicyList.
func (in *NgrokTrafficPolicyList) DeepCopy() *NgrokTrafficPolicyList {
	if in == nil {
		return nil
	}
	out := new(NgrokTrafficPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NgrokTrafficPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NgrokTrafficPolicySpec) DeepCopyInto(out *NgrokTrafficPolicySpec) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NgrokTrafficPolicySpec.
func (in *NgrokTrafficPolicySpec) DeepCopy() *NgrokTrafficPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NgrokTrafficPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NgrokTrafficPolicyStatus) DeepCopyInto(out *NgrokTrafficPolicyStatus) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NgrokTrafficPolicyStatus.
func (in *NgrokTrafficPolicyStatus) DeepCopy() *NgrokTrafficPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NgrokTrafficPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficPolicyCfg) DeepCopyInto(out *TrafficPolicyCfg) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.Reference != nil {
		in, out := &in.Reference, &out.Reference
		*out = new(K8sObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficPolicyCfg.
func (in *TrafficPolicyCfg) DeepCopy() *TrafficPolicyCfg {
	if in == nil {
		return nil
	}
	out := new(TrafficPolicyCfg)
	in.DeepCopyInto(out)
	return out
}
