apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-ingress-controller.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: {{ include "kubernetes-ingress-controller.fullname" . }}-leader
