---
name: ngrok Ingress Controller Bug Report
description: Report an issue in the ngrok Ingress Controller
labels: ["bug", "area/controller", "needs-triage"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!

      Note, you do not need to create an issue if you have a change ready to submit.
      You can open a [pull request](https://github.com/ngrok/kubernetes-ingress-controller/pulls) immediately instead.
- type: input
  attributes:
    label: Kubernetes Version
    description: Which Kubernetes Version do you use?
  validations:
    required: true
- type: input
  attributes:
    label: Helm Chart Version
    description: Which version of the Helm chart do you use?
  validations:
    required: true
- type: input
  attributes:
    label: Ingress Controller Version
    description: Which version of the Ingress controller do you use?
  validations:
    required: true
- type: textarea
  attributes:
    label: System Info
    description: We want to know your OS, architecture etc.
    placeholder: >
      Run `uname -a` or `systeminfo` and copy the output here.
  validations:
    required: true
- type: textarea
  attributes:
    label: Kubernetes Logs
    description: We want to see relevant kubernetes logs showing error messages
or helpful debugging information
    placeholder: >
      Run `kubectl logs -l app.kubernetes.io/name=kubernetes-ingress-controller` and copy the output here.
  validations:
    required: true
- type: textarea
  attributes:
    label: Helm Chart configuration
    description: Additional description of your Helm Chart configuration.
    placeholder: >
      Enter any relevant details of your Helm Chart configuration. Maybe you can
      paste your `values.yaml` or important parts of it here? Make sure to surround the code
      you paste with ``` ```.
- type: textarea
  attributes:
    label: What happened
    description: Describe what happened.
    placeholder: >
      Please provide the context in which the problem occurred and explain what happened
  validations:
    required: true
- type: textarea
  attributes:
    label: What you think should happen instead
    description: What do you think went wrong?
    placeholder: >
      Please explain why you think the behavior you observed is incorrect. It is extremely helpful
      if you copy & paste the fragment of logs showing the exact error messages or wrong behavior.
- type: textarea
  attributes:
    label: How to reproduce
    description: What should we do to reproduce the problem?
    placeholder: >
      Please provide a reproducible step-by-step case of how to reproduce the problem as minimally and
      precisely as possible. It will greatly help us in figuring out the root cause of the problem and fixing it.
- type: markdown
  attributes:
    value: "Thank you for help in improving the ngrok Ingress Controller!"
