# ClusterRole: ngrok-operator-operatorconfiguration-viewer-role
# Generated: 2026-04-07T15:32:47Z

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: ngrok-operator
    meta.helm.sh/release-namespace: ngrok-operator
  creationTimestamp: "2026-04-07T15:25:18Z"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: ngrok-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ngrok-operator
    app.kubernetes.io/part-of: ngrok-operator
    app.kubernetes.io/version: 0.20.3
    helm.sh/chart: ngrok-operator-0.22.2
  name: ngrok-operator-operatorconfiguration-viewer-role
  resourceVersion: "631"
  uid: 1aa3a517-5476-40e9-97ee-7752000a2c66
rules:
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - operatorconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - operatorconfigurations/status
  verbs:
  - get
