{{- if and .Values.bindings.enabled .Values.bindings.ngrokCA }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ngrok-intermediate-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
data:
  root.crt: |
    {{- .Values.bindings.ngrokCA | nindent 4 }}
{{- end }}
