{{- if and .Values.features.bindings.enabled (not .Values.apiManager.config.oneClickDemoMode) }}
{{- $component := "bindings-forwarder" }}
{{- $rbacChecksum := include (print $.Template.BasePath "/bindings-forwarder/role.yaml") . | sha256sum }}
{{- $forwarder := .Values.bindingsForwarder }}
{{- $configChecksum := include "ngrok-operator.componentConfig" (dict "context" $ "config" $forwarder.config) | sha256sum }}
{{- $configEnvKeys := list
  (list "NGROK_OPERATOR_DESCRIPTION" "description")
  (list "NGROK_OPERATOR_LOG_LEVEL" "log.level")
  (list "NGROK_OPERATOR_LOG_FORMAT" "log.format")
  (list "NGROK_OPERATOR_LOG_STACKTRACE_LEVEL" "log.stacktraceLevel")
}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  name: {{ include "ngrok-operator.fullname" . }}-bindings-forwarder
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with (include "ngrok-operator.commonAnnotations" .) }}
    {{- . | nindent 4 }}
    {{- end }}
    checksum/rbac: {{ $rbacChecksum }}
spec:
  replicas: {{ $forwarder.replicaCount }}
  {{- if $forwarder.updateStrategy }}
  strategy:
    {{- toYaml $forwarder.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ngrok-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      annotations:
        {{- if $forwarder.podAnnotations }}
          {{- toYaml $forwarder.podAnnotations | nindent 8 }}
        {{- end }}
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
        checksum/rbac: {{ $rbacChecksum }}
        checksum/config: {{ $configChecksum }}
      labels:
        {{- include "ngrok-operator.selectorLabels" . | nindent 8 }}
        {{- if $forwarder.podLabels }}
          {{- toYaml $forwarder.podLabels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      {{- if $forwarder.priorityClassName }}
      priorityClassName: {{ $forwarder.priorityClassName | quote }}
      {{- end }}
      {{- if $forwarder.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $forwarder.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if $forwarder.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" $forwarder.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" $forwarder.podAffinityPreset "component" $component "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" $forwarder.podAntiAffinityPreset "component" $component "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" $forwarder.nodeAffinityPreset.type "key" $forwarder.nodeAffinityPreset.key "values" $forwarder.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- with $forwarder.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ with $forwarder.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $forwarder.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "ngrok-operator.bindings.forwarder.serviceAccountName" . }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: forwarder
        image: {{ include "ngrok-operator.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /ngrok-operator
        args:
        - bindings-forwarder-manager
        - --release-name={{ .Release.Name }}
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        - --manager-name={{ include "ngrok-operator.fullname" . }}-bindings-forwarder
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: NGROK_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              key: AUTHTOKEN
              name: {{ include "ngrok-operator.credentialsSecretName" . }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HELM_RELEASE_NAME
          value: {{ .Release.Name | quote }}
        {{- include "ngrok-operator.configEnv" (dict "context" $ "component" "bindings-forwarder" "keys" $configEnvKeys) | trim | nindent 8 }}
        {{- range $key, $value := $forwarder.extraEnv }}
        - name: {{ $key }}
          value: {{- toYaml $value | nindent 12 }}
        {{- end }}
        {{- if $forwarder.extraVolumeMounts }}
        volumeMounts:
        {{- toYaml $forwarder.extraVolumeMounts | nindent 8 }}
        {{- end }}
        {{- if $forwarder.lifecycle }}
        lifecycle:
        {{- toYaml $forwarder.lifecycle | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
        {{- toYaml $forwarder.resources | nindent 10 }}
      {{- if $forwarder.extraVolumes }}
      volumes:
        {{- toYaml $forwarder.extraVolumes | nindent 8 }}
      {{- end }}
{{- end }}
