{{- if .Values.bindings.enabled }}
{{ $bindingForwarderRole := printf "%s-bindings-forwarder" (include "ngrok-operator.fullname" .) }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $bindingForwarderRole }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - bindings.k8s.ngrok.com
  resources:
  - boundendpoints
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ngrok.k8s.ngrok.com
  resources:
  - kubernetesoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ngrok-operator.fullname" . }}-bindings-forwarder-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $bindingForwarderRole }}
subjects:
- kind: ServiceAccount
  name: {{ template "ngrok-operator.bindings.forwarder.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
