{{- if .Values.bindings.enabled }}
{{- if .Values.bindings.forwarder.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ngrok-operator.bindings.forwarder.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- if .Values.bindings.forwarder.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.bindings.forwarder.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
