# permissions for end users to view ngrokmodulesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ngrokmoduleset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-ingress-controller
    app.kubernetes.io/part-of: kubernetes-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: ngrokmoduleset-viewer-role
rules:
- apiGroups:
  - ingress.k8s.ngrok.com
  resources:
  - ngrokmodulesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.k8s.ngrok.com
  resources:
  - ngrokmodulesets/status
  verbs:
  - get
