name: Action - Build and Test
description: "Build and test the operator (with optional e2e tests)"

inputs:
  run-e2e:
    description: "Run e2e tests"
    required: false
    default: "false"
  ngrok-api-key:
    description: "NGROK_API_KEY for e2e tests, if enabled"
    required: false
    default: "fake-api-key"
  ngrok-authtoken:
    description: "NGROK_AUTHTOKEN for e2e tests, if enabled"
    required: false
    default: "fake-authtoken"
  kind-version:
    description: "KIND version to use"
    required: false
    default: "v0.26.0"

runs:
  using: "composite"
  steps:
    - uses: engineerd/setup-kind@v0.6.2
      with:
        version: ${{ inputs.kind-version }}
        name: ngrok-operator

    - shell: bash
      run: |
        kubectl get nodes
        kubectl get pods -A

    - name: Build
      shell: bash
      run: nix develop --command make build

    - name: Test
      shell: bash
      run: nix develop --command make test

    - name: Build the Docker image
      shell: bash
      run: nix develop --command make docker-build

    - name: Deploy controller to local cluster
      shell: bash
      env:
        # deploy with 1-click demo mode when not running e2e tests
        DEPLOY_ONE_CLICK_DEMO_MODE: ${{ inputs.run-e2e == 'true' &&  'false' || 'true' }}
        NGROK_API_KEY: ${{ inputs.ngrok-api-key }}
        NGROK_AUTHTOKEN: ${{ inputs.ngrok-authtoken }}
        E2E_BINDING_NAME: k8s/e2e-${{ github.run_id }}
      run: |
        # create some namespaces for bindings tests
        kubectl create ns e2e || true

        # deploy ngrok-op for e2e tests
        nix develop --command make deploy_for_e2e

    - name: Check if operator is up
      shell: bash
      run: |
        kubectl get nodes
        kubectl get pods -A
        kubectl -n ngrok-operator wait --for=condition=ready pod -l app.kubernetes.io/name=ngrok-operator --timeout=1m || true
        kubectl get pods -A
        kubectl -n ngrok-operator describe pod -l app.kubernetes.io/name=ngrok-operator

    - name: Run e2e tests
      shell: bash
      if: ${{ inputs.run-e2e == 'true' }}
      run: nix develop --command make e2e-tests

    # best effort to remove ngrok k8s resources from cluster
    # this allows our finalizers to delete upstream ngrok API resources too
    # that hopefully helps not pollute our ngrok-operator-ci account
    - name: Cleanup e2e tests
      shell: bash
      if: ${{ always() && inputs.run-e2e == 'true' }}
      run: |
        nix develop --command make e2e-clean
