{{- if .Values.apiManager.podDisruptionBudget.create }}
{{ $component := "controller"}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ngrok-operator.fullname" . }}-controller-pdb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  {{- with (include "ngrok-operator.commonAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.apiManager.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.apiManager.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.apiManager.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.apiManager.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ngrok-operator.selectorLabels" . | nindent 6 }}
      {{- if .Values.apiManager.podLabels }}
        {{- toYaml .Values.apiManager.podLabels | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: {{ $component }}
{{- end }}
