{{- $watchNamespace := include "ngrok-operator.watchNamespace" . -}}
{{- $isNamespaced := ne $watchNamespace "" -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ngrok-operator.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ngrok-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ngrok-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ template "ngrok-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- if $isNamespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ngrok-operator.fullname" . }}-manager-rolebinding
  namespace: {{ $watchNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ngrok-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "ngrok-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ngrok-operator.fullname" . }}-manager-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ngrok-operator.fullname" . }}-manager-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ template "ngrok-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ngrok-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ngrok-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "ngrok-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
