{{- if .Values.features.ingress.enabled }}
{{- if .Values.features.ingress.ingressClass.create -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  name: {{ .Values.features.ingress.ingressClass.name }}
  {{- $annotations := dict }}
  {{- if .Values.features.ingress.ingressClass.default }}
  {{- $_ := set $annotations "ingressclass.kubernetes.io/is-default-class" "true" }}
  {{- end }}
  {{- $annotations = merge $annotations (.Values.commonAnnotations | default dict) }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  controller: {{ .Values.features.ingress.controllerName }}
{{- end}}
{{- end}}
