apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: KubernetesOperator
metadata:
  name: {{ .Release.Name }}-ngrok-operator
  namespace: {{ .Release.Namespace }}
spec:
  binding:
    allowedURLs:
    {{- toYaml .Values.bindings.allowedURLs | nindent 4 }}
    name: {{ .Values.bindings.name }}
    tlsSecretName: {{ printf "%s-default-tls" .Release.Name }}
  deployment:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    version: {{ .Chart.Version }}
  enabledFeatures:
  {{- if .Values.ingress.enabled }}
  - ingress
  {{- end }}
  {{- if .Values.gateway.enabled }}
  - gateway
  {{- end }}
  {{- if .Values.bindings.enabled }}
  - bindings
  {{- end }}
  region: {{ .Values.region }}
