{{- $component := "operator" }}
apiVersion: ngrok.k8s.ngrok.com/v1beta1
kind: OperatorConfiguration
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  # id: "" # unset, to be filled in on registration
  # uri: "" # unset, to be filled in on registration
  description: "{{ .Values.description }}"
  metadata: "{{ .Values.metaData }}"
  appVersion: "{{ .Release.appVersion }}"
  enabledFeatures:
  - ingress # enum, always enabled for now
  {{- if .Values.bindings.enabled }}
  - bindings # enum
  {{- end }}
  {{- if .Values.useExperimentalGatewayApi }}
  - gateway # enum
  {{- end }}
  apiURL: "{{ .Values.apiURL }}"
  region: "{{ .Values.region }}"
  clusterDomain: "{{ .Values.clusterDomain }}"
