{{- if .Values.crdAccessRoles.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ngrok-operator.fullname" . }}-boundendpoint-editor-role
  labels:
    app.kubernetes.io/component: rbac
    {{- include "ngrok-operator.labels" . | nindent 4 }}
  {{- with .Values.crdAccessRoles.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - bindings.k8s.ngrok.com
  resources:
  - boundendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bindings.k8s.ngrok.com
  resources:
  - boundendpoints/status
  verbs:
  - get
{{- end }}
