name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_BUILDX_PLATFORMS: linux/amd64,linux/arm64

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
      chartyaml: ${{ steps.filter.outputs.chartyaml }}
      go: ${{ steps.filter.outputs.go }}
      tag: ${{ steps.filter.outputs.tag }}
    permissions:
      contents: read
      pull-requests: read
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - id: filter
      uses: dorny/paths-filter@v2.11.1
      with:
        filters: |
          chartyaml:
            - 'helm/ingress-controller/Chart.yaml'
          charts:
            - 'helm/ingress-controller/**'
            - 'scripts/e2e.sh'
          go:
            - '**.go'
            - 'go.mod'
            - 'go.sum'
            - 'cmd/**'
            - 'internal/**'
            - 'pkg/**'
            - 'Dockerfile'
            - 'scripts/e2e.sh'
            - 'VERSION'
          tag:
            - 'VERSION'

  # Make sure that Kubebuilder autogenerated files are up to date. 
  kubebuilder-diff:
    name: Kubebuilder Diff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19 # Use the latest
    - name: Generate manifests
      run: make manifests
    - name: Fail if there are uncommited manifest changes
      run: |
        git diff --exit-code
        git diff --cached --exit-code

  build-images:
    name: Build Images
    needs:
    - changes
    - kubebuilder-diff
    if: needs.changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - id: buildx-setup
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: ${{ env.DOCKER_BUILDX_PLATFORMS }}
    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: ${{ steps.buildx-setup.outputs.platforms }}
        push: false
        tags: ngrok/ngrok-ingress-controller:latest

  build:
    runs-on: ubuntu-latest
    needs:
    - changes
    - kubebuilder-diff
    if: |
      (needs.changes.outputs.go == 'true') ||
      (needs.changes.outputs.charts == 'true')
    steps:
    - uses: actions/checkout@v3

    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'
    - run: |
        kubectl get nodes
        kubectl get pods -A

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19 # Use the latest

    - name: Build
      run: make build

    - name: Test and Lint
      run: make test

    - name: Build the Docker image
      run: make docker-build

    - name: Deploy controller to local cluster
      run: make deploy

    - name: Check if controller is up
      run: |
        kubectl get nodes
        kubectl get pods -A

  helm:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [changes]
    if: needs.changes.outputs.charts == 'true'
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-helm@v3
      with:
        version: v3.10.0
    - name: Lint Helm Chart
      run: make helm-lint
    - name: Helm Unit Tests
      run: make helm-test
