name: 'Generate full install manifests'

on:
  push:
    branches:
    - main
    paths:
    - 'helm/**/*'
    - 'Makefile'
    - 'tools/make/**'

permissions:
  contents: write

jobs:
  update-full-install:
    name: Update full install
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup nix
        uses: ./.github/actions/nix-setup
      - name: Run helm template
        run: make manifest-bundle
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update full install manifests file
