name: 'Helm Readme Generator'

on:
  pull_request_target:
    branches:
    - main
    paths:
    - 'helm/*/values.yaml'
permissions:
  contents: write
jobs:
  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm@2.6.1
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute readme-generator-for-helm
        working-directory: helm/ngrok-operator
        run: |
          readme-generator --values "values.yaml" --readme "README.md" --schema "/tmp/schema.json"
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md with readme-generator-for-helm
