name: Pull Request Labeler
on:
  pull_request_target:
    types:
    - opened
    - edited
    - reopened
    - synchronize

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  size-labeler:
    name: Size
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Apply size label
      uses: ngrok/pr-size-labeler@d5a95a01bbe2eca3f692d0809edb0aeb56c3bd18
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

